import { z } from 'zod'

export const createDealSchema = z.object({
  accountId: z.union([z.string().min(1, 'Account is required'), z.number()]),
  accountName: z.string().optional(),
  dealName: z.string().optional(),
  ticketId: z.union([z.string(), z.number()]).optional(),
  ticketNumber: z.union([z.string(), z.number()]).optional(),
  dealType: z.string().optional(),
  loanType: z.string().optional(),
  typeOfLogin: z.string().optional(),
  typeOfCaseLogin: z.string().optional(),
  ticketLogin: z.string().optional(),
  dealStage: z.string().optional(),
  dealStatus: z.string().optional(),

  disbursedAmount: z.string().optional(),
  sanctionAmount: z.string().optional(),
  approvedAmount: z.string().optional(),
  amountRequired: z.string().optional(),
  processingFees: z.string().optional(),
  dealExpectedClosing: z.string().optional(),
  dealStatusClosing: z.string().optional(),
  mmCharges: z.string().optional(),
  insuranceAmount: z.string().optional(),
  pfPercentage: z.string().optional(),
  rateOfInterest: z.string().optional(),
  interestType: z.string().optional(),

  dealCallBackDatetime: z.string().optional(),
  disbursementDate: z.string().optional(),
  lenderLoginDate: z.string().optional(),
  lenderLoginType: z.string().optional(),
  loanStartDate: z.string().optional(),
  loanEndDate: z.string().optional(),
  targetedDisbursementDate: z.string().optional(),
  tenure: z.union([z.string(), z.number()]).optional(),

  lenderCode: z.string().optional(),
  lenderName: z.string().optional(),
  customerRejectionReason: z.string().optional(),
  customerRejectionStatusExplanation: z.string().optional(),
  lenderRejectionReason: z.string().optional(),
  lenderRejectionStatusExplanation: z.string().optional(),
  partnerCode: z.string().optional(),
  paymentReceipt: z.string().optional(),
  potential: z.string().optional(),
  product: z.string().optional(),
})

export type CreateDealFormValues = z.infer<typeof createDealSchema>
